### ISSUE TITLE
Audio chunk timestamps

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat-speechAnalyzer#7]
We will need to capture the timestamps of the individual incoming audio chunks.

@vincentraymond-ua Could you please implement this? Basically, every time an audio chunk reaches the speechAnalyzer agent over websocket, it should publish a message to the message bus to the topic `agent/speech_analyzer/chunk_metadata` (or some better name if you come up with one!) with the timestamp, chunk size in bytes, participant_id, and the `header` and `msg` parts of the common TA3 message format.

**Comment by vincentraymond-ua** [comment]
Yes, I will implement this. It should be fairly simple to integrate into our existing message processing pipeline.

**Comment by adarshp** [comment]
Thanks @vincentraymond-ua !

**Comment by adarshp** [comment]
Closing this since we decided that the individual audio chunk timestamps placed a large load on the message bus, and had less than optimal interactions with replay operations.
