### ISSUE TITLE
Agent info message

### ISSUE THREAD

**Issue by adarshp** [ml4ai/tomcat-speechAnalyzer#8]
With data collection starting soon and the new features that are in the pipeline (e.g. vocalic feature extraction, sentiment analysis), it makes sense to add the agent version info message proposed by JCR here:

https://gitlab.asist.aptima.com/asist/testbed/-/blob/develop/MessageSpecs/Agent/versioninfo/agent_versioninfo.md

While this is a draft, I doubt that there will be large changes to the format, so I think we can go ahead and add it.

This message should be published to the message bus whenever there is a trial start message published on the bus.

For now, just include the agent_name, version, and owner fields in the data part of the message. We can update the format when it gets finalized in the testbed WG.

**Comment by vincentraymond-ua** [comment]
Okay, I have started working on this in the agent_info_message-feature branch.

**Comment by adarshp** [comment]
Closed by #10
